#!/usr/bin/env node

const exec = require('child_process').exec;
const fs = require('fs');
const parseNode = node => {
  let returnVal = {
    focused: false,
    open: false
  };
  if (node.window_properties && node.window_properties.class.match(/calculator/i) !== null) {
    returnVal.open = true;
  }
  if (node.focused) {
    if (node.window_properties.class.match(/calculator/i) !== null) {
      returnVal.focused = true;
    }
    const text = JSON.stringify(node);
      // exec(`notify-send "${text}"`);
  }
  node.nodes.concat(node.floating_nodes).forEach(loopNode => {
    let loopReturnValue = parseNode(loopNode);
    if (loopReturnValue.focused) {
        returnVal.focused = true;
    }
    if (loopReturnValue.open) {
        returnVal.open = true;
    }
  });
  return returnVal;
}

const child = exec('i3-msg -t get_tree', (error, stdout, sterr) => {
  const tree = JSON.parse(stdout);
  const parseResults = parseNode(tree);
  if (parseResults.focused) {
    exec('i3-msg "[class=\"Gnome-calculator\"] move scratchpad"');
  } else if (parseResults.open) {
    exec('i3-msg "[class=\"Gnome-calculator\"] move workspace current"');
  } else {
    exec('gnome-calculator &');
  }
});
